### ISSUE TITLE
Need to cope with paths with arbitrary depth

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/images-api#4]
The following image doesn't appear to work with the images API:
> https://greenstand.org/fileadmin/02-graphics/12-externally-linked/no-planter-image.png

Using the same format as Statically.io, this should be expected by the API as:
> https://prod-k8s.treetracker.org/images/img/greenstand.org/fileadmin/02-graphics/12-externally-linked/w=300/no-planter-image.png

This seems to be because it has a deep path, which we need to support.

**Comment by Kpoke** [comment]
@nmcharlton this has been fixed and deployed to the dev and test environment. Kindly let me know if it works as expected so I can deploy it to production

**Comment by Kpoke** [comment]
@nmcharlton this has been fixed and deployed to the dev environment.
