### ISSUE TITLE
Observed timeout error: upstream request timeout

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/images-api#9]
THe request: https://dev-k8s.treetracker.org/images/img/treetracker-production-images.s3.eu-central-1.amazonaws.com/w=208,h=232/2021.12.20.10.08.15_-19.158849191950235_47.592259844822465_3736716C-D085-459B-B61E-9514B170533D_EB695E39-ECEE-45A9-B248-D401BEB7CA73.jpg

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/5744708/190108687-1b4ef429-e3bc-40d8-927a-5e3562265ca0.png">

**Comment by dadiorchen** [comment]
@Kpoke is this because the api gateway timeout is too short? this image is a little huge

**Comment by dadiorchen** [comment]
https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.12.20.10.08.08_-19.15886409373788_47.592340944792895_48B9241F-674F-40BD-9D27-A46049767495_98D2A2E4-6AB7-407E-B882-B8B49A598EE0.jpg"

**Comment by Kpoke** [comment]
This is a cloud/kubernetes issue, not sure what is causing it. I have experienced this previously with some of the other APIs. You could reach out to the cloud team
